spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/UDEE
    url: jdbc:mysql://localhost:3307/UDEE?serverTimezone=UTC
    username: root
    #password:
    password: Renata2000
  jpa:
    show-sql : true
    hibernate:
      ddl-auto: none