spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/UDEE
    #url: jdbc:mysql://localhost:3307/UDEE?serverTimezone=UTC
    #Docker# url: jdbc:mysql://MySQL-docker-udee/UDEE?serverTimezone=UTC
    username: root
    #password:
    #Password contenedor de docker# password:root
    password: Renata2000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql : true
    hibernate:
      ddl-auto: none
    database: mysql

